CREATE OR REPLACE TABLE "STAGE"."ETH"."BLOCK_METADATA" (
    "NUMBER" INTEGER NOT NULL
    , "TIMESTAMP" INTEGER NOT NULL
    , "DIFFICULTY" INTEGER NOT NULL
    , "BASEFEEPERGAS" INTEGER NOT NULL
    , "GASLIMIT" INTEGER NOT NULL
    , "GASUSED" INTEGER NOT NULL
    , "HASH" STRING NOT NULL
    , "MINER" STRING NOT NULL
    , "SIZE" INTEGER NOT NULL
    , "NONCE" STRING NOT NULL
);