CREATE OR REPLACE TABLE "STAGE"."ETH"."BLOCK_TRANSACTIONS" (
    "ACCESSLIST" FLOAT
    , "BLOCKHASH" VARCHAR(66)
    , "BLOCKNUMBER" INTEGER
    , "CHAINID" VARCHAR(3)
    , "FROM" VARCHAR(42)
    , "GAS" INTEGER
    , "GASPRICE" INTEGER
    , "HASH" VARCHAR(66)
    , "INPUT" VARCHAR(5578)
    , "MAXFEEPERGAS" VARCHAR(100)
    , "MAXPRIORITYFEEPERGAS" VARCHAR(100)
    , "NONCE" INTEGER
    , "R" VARCHAR(66)
    , "S" VARCHAR(66)
    , "TO" VARCHAR(42)
    , "TRANSACTIONINDEX" INTEGER
    , "TYPE" VARCHAR(3)
    , "V" INTEGER
    , "VALUE" FLOAT
);